name: modmesh_install

on:
  push:
  pull_request:
  schedule:
    - cron: '34 17 * * *'

jobs:
  build:

    name: test after setup.py

    if: ${{ github.event_name != '' || (github.event_name == '' && github.repository_owner == 'solvcon') }}

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-20.04, macos-11]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qy install \
            sudo curl git build-essential make cmake libc6-dev gcc g++ \
            clang-tidy-10 \
            python3 python3-dev python3-venv
        sudo ln -s "$(which clang-tidy-10)" "$(dirname $(which clang-tidy-10))/clang-tidy"
        sudo pip3 install setuptools
        sudo pip3 install numpy pytest flake8

    - name: dependency (macos)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        brew install python3 llvm
        ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
        pip3 install -U setuptools
        pip3 install -U numpy pytest flake8

    - name: dependency (manual)
      run: sudo ${GITHUB_WORKSPACE}/contrib/dependency/install.sh pybind11

    - name: show dependency
      run: |
        echo "gcc path: $(which gcc)"
        echo "gcc version: $(gcc --version)"
        echo "cmake path: $(which cmake)"
        echo "cmake version: $(cmake --version)"
        echo "python3 path: $(which python3)"
        echo "python3 version: $(python3 --version)"
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        echo "pytest path: $(which pytest)"
        echo "pytest version: $(pytest --version)"
        echo "clang-tidy path: $(which clang-tidy)"
        echo "clang-tidy version: $(clang-tidy -version)"
        echo "flake8 path: $(which flake8)"
        echo "flake8 version: $(flake8 --version)"

    - name: build_ext
      run: |
        python3 setup.py build_ext \
          --cmake-args="-DBUILD_QT=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(which python3)" \
          --make-args="VERBOSE=1"

    - name: install
      run: |
        case "$(uname -s)" in
            Linux*) cmdprefix=sudo;;
            *) cmdprefix=
        esac
        ${cmdprefix} python3 setup.py install

    - name: pytest
      run: |
        rm -rf tmp/
        mkdir -p tmp/
        cp -a tests tmp/
        cd tmp/
        python3 -c "import modmesh; print(modmesh._modmesh.__file__)"
        pytest -v
        cd ..
